<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Configurations>Debug;Release;</Configurations>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)' == 'ARM64'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>